name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Give execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Give execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --info

  coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install bc
        run: sudo apt-get install bc
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Give execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with coverage
        run: ./gradlew koverReport

      - name: Move coverage report to output directory
        run: |
          mkdir -p coverage-reports
          cp -r app/build/reports/kover/project-html coverage-reports/

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: kover-report
          path: coverage-reports/project-html
